package com.mycompany.webproject;
// Generated May 13, 2015 8:02:14 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Association generated by hbm2java
 */
@Entity
@Table(name="association"
    ,catalog="restdb"
)
public class Association  implements java.io.Serializable {


     private AssociationId id;
     private Address address;
     private Certificate certificate;
     private Person person;
     private String name;

    public Association() {
    }

	
    public Association(AssociationId id, Address address, Certificate certificate, Person person) {
        this.id = id;
        this.address = address;
        this.certificate = certificate;
        this.person = person;
    }
    public Association(AssociationId id, Address address, Certificate certificate, Person person, String name) {
       this.id = id;
       this.address = address;
       this.certificate = certificate;
       this.person = person;
       this.name = name;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idAssociation", column=@Column(name="id_association", nullable=false) ), 
        @AttributeOverride(name="addressIdaddress", column=@Column(name="address_idaddress", nullable=false) ), 
        @AttributeOverride(name="personIdperson", column=@Column(name="person_idperson", nullable=false) ), 
        @AttributeOverride(name="certificateIdcertificate", column=@Column(name="certificate_idcertificate", nullable=false) ) } )
    public AssociationId getId() {
        return this.id;
    }
    
    public void setId(AssociationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="address_idaddress", nullable=false, insertable=false, updatable=false)
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="certificate_idcertificate", nullable=false, insertable=false, updatable=false)
    public Certificate getCertificate() {
        return this.certificate;
    }
    
    public void setCertificate(Certificate certificate) {
        this.certificate = certificate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="person_idperson", nullable=false, insertable=false, updatable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


