package com.mycompany.webproject;
// Generated May 13, 2015 8:02:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssociationId generated by hbm2java
 */
@Embeddable
public class AssociationId  implements java.io.Serializable {


     private int idAssociation;
     private int addressIdaddress;
     private int personIdperson;
     private int certificateIdcertificate;

    public AssociationId() {
    }

    public AssociationId(int idAssociation, int addressIdaddress, int personIdperson, int certificateIdcertificate) {
       this.idAssociation = idAssociation;
       this.addressIdaddress = addressIdaddress;
       this.personIdperson = personIdperson;
       this.certificateIdcertificate = certificateIdcertificate;
    }
   


    @Column(name="id_association", nullable=false)
    public int getIdAssociation() {
        return this.idAssociation;
    }
    
    public void setIdAssociation(int idAssociation) {
        this.idAssociation = idAssociation;
    }


    @Column(name="address_idaddress", nullable=false)
    public int getAddressIdaddress() {
        return this.addressIdaddress;
    }
    
    public void setAddressIdaddress(int addressIdaddress) {
        this.addressIdaddress = addressIdaddress;
    }


    @Column(name="person_idperson", nullable=false)
    public int getPersonIdperson() {
        return this.personIdperson;
    }
    
    public void setPersonIdperson(int personIdperson) {
        this.personIdperson = personIdperson;
    }


    @Column(name="certificate_idcertificate", nullable=false)
    public int getCertificateIdcertificate() {
        return this.certificateIdcertificate;
    }
    
    public void setCertificateIdcertificate(int certificateIdcertificate) {
        this.certificateIdcertificate = certificateIdcertificate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AssociationId) ) return false;
		 AssociationId castOther = ( AssociationId ) other; 
         
		 return (this.getIdAssociation()==castOther.getIdAssociation())
 && (this.getAddressIdaddress()==castOther.getAddressIdaddress())
 && (this.getPersonIdperson()==castOther.getPersonIdperson())
 && (this.getCertificateIdcertificate()==castOther.getCertificateIdcertificate());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAssociation();
         result = 37 * result + this.getAddressIdaddress();
         result = 37 * result + this.getPersonIdperson();
         result = 37 * result + this.getCertificateIdcertificate();
         return result;
   }   


}


