package com.mycompany.webproject;
// Generated May 13, 2015 8:02:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Certificate generated by hbm2java
 */
@Entity
@Table(name="certificate"
    ,catalog="restdb"
)
public class Certificate  implements java.io.Serializable {


     private Integer idcertificate;
     private String number;
     private Date dateStart;
     private Date dateEnd;
     private Set<Association> associations = new HashSet<Association>(0);

    public Certificate() {
    }

    public Certificate(String number, Date dateStart, Date dateEnd, Set<Association> associations) {
       this.number = number;
       this.dateStart = dateStart;
       this.dateEnd = dateEnd;
       this.associations = associations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcertificate", unique=true, nullable=false)
    public Integer getIdcertificate() {
        return this.idcertificate;
    }
    
    public void setIdcertificate(Integer idcertificate) {
        this.idcertificate = idcertificate;
    }

    
    @Column(name="number", length=45)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_start", length=19)
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_end", length=19)
    public Date getDateEnd() {
        return this.dateEnd;
    }
    
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="certificate")
    public Set<Association> getAssociations() {
        return this.associations;
    }
    
    public void setAssociations(Set<Association> associations) {
        this.associations = associations;
    }




}


